### ISSUE TITLE
How is this supposed to be done now?

### ISSUE THREAD

**Issue by robross0606** [TotallyInformation/node-red-contrib-globalgetset#2]
Your ReadMe says "Recent updates (0.13) to Node-Red mean that there are now in-built methods for handing context and global variables in more than just the function node."  However, I really cannot figure out how or where you're supposed to do this other than writing JavaScript.  I would really appreciate if you could give me a hint as to how this is done "in more than just the function node"?

**Comment by robross0606** [comment]
I think I just found it.  Not super intuitive, but I found the change log for version 0.13 where it talks about updates to the Change Node.  Thanks for the hint!

**Comment by TotallyInformation** [comment]
Hi, you might want to revisit the Node-RED docs. Node-RED is still a rapidly changing tool so it can be hard to keep up.

You are correct that the Change node is now the best way to do what this node did for a short while. In fact, the change node is incredibly powerful with lots of ways to manipulate data including the excellent JSONata for transforming JSON.

You've reminded me though to update the README for this to mark it as deprecated.
